alias ls="eza --icons --color=auto --group-directories-first"
alias ll="ls --long --group --header"
alias la="ll --all"
alias cat="bat"
alias grep="grep --color=auto"
alias shell="exec $SHELL -l"
alias fk="sudo !!"
alias gs="git status --short"
alias gd="git diff --output-indicator-new=' ' --output-indicator-old=' '"
alias ga="git add"
alias gf="git fetch"
alias gr="git reset"
alias gap="git add --patch"
alias gc="git commit"
alias gp="git push"
alias gpf="git push --force-with-lease"
alias gu="git pull"
alias gl='git log --all --graph --pretty=format:"%C(magenta)%h %C(white)%an %ar%C(auto)%d%n%s%n"'
alias gb="git branch"
alias gi="git init"
alias gcl="git clone"
alias gco="git checkout"
alias gsw="git switch"
alias grh="git reset --hard HEAD"

alias fzf="fzf --style full --preview 'fzf-preview.sh {}' --bind 'focus:transform-header:file --brief {}'"
alias fuzzynvim='nvim "$(fzf -m --preview="bat --color=always {}")"'
